version: '3.1'

services:

  db:
    image: mysql
    restart: always
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: salman
      MYSQL_PASSWORD: login14ms
    volumes:
        - mysql-data:/var/lib/mysql


  adminer:
    image: adminer
    container_name: adminer_container
    restart: always
    ports:
      - 8080:8080
volumes:
  mysql-data:
    driver: local
